name: deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build website
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      VUE_APP_SERVER_URL: https://furutsu.amanbolat.com
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: build project
        working-directory: web
        run: |
          npm install
          npm run build
      - name: create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: web/dist

  deploy:
    name: upload to aws s3
    runs-on: ubuntu-latest
    needs: [build]
    env:
      BUCKET_NAME: furutsu.amanbolat.com-static
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: copy files
        run: |
          aws s3 sync ./dist/ ${BUCKET_NAME} --delete --exclude index.html --exclude sw.js --acl public-read --cache-control public,max-age=604800
          aws s3 cp ./dist/index.html ${BUCKET_NAME} --acl public-read --cache-control public,max-age=0